### PR TITLE
Support multi-module projects

### PR DESCRIPTION
**Pull request by dajmaki**
- Aggregate dependencies from all modules and output
  project-info.json only after last module.

- Skip dependencies without backing repositories
  (to not break buildMaven in nixpkgs due to missing
   'authenticated' attribute).

### CODE REVIEW

**Comment by dajmaki** [comment]
This should address the open issues #4 and #5.

Not sure if skipping the dependencies that are only local is the right thing
to do here. It could also be fixed in build-maven.nix.

**Comment by shlevy** [comment]
I'm pretty sure skipping dependencies is the wrong thing to do, the build might go through but the result won't have needed deps. One possibility is if a dep is already in the local cache to try to determine some other way if it needs authentication?

Why did you turn off the streaming output?

Can you break these up into separate PRs or at least separate commits? There's a lot to disentangle here.

**Comment by dajmaki** [comment]
I'll remove the skipping of the dependencies.
In what way does this turn off streaming output? The steps to gather the sets of dependencies
is very fast compared (few hundred milliseconds in the project I have here) to the actual
output phase and calls to handleDependency.

**Comment by shlevy** [comment]
Ah, never mind, misunderstood. So to clarify what's going on here, `execute` is called for each project?

**Comment by dajmaki** [comment]
Yes, execute gets called once for each module defined in the root pom.xml.

**Comment by shlevy** [comment]
New release propagating now.

**Pull request merged**
